# Base configs
baseurl: "https://astro.sick-simon.de"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Astrophotography by Sick Simon"
subtitle: "See the world through my eyes!"
author: "Sick Simon"
header:
 title: "Photography"
 subtitle: "by Sick Simon"
footer:
 name: "Hey there, my name is Simon"
 bio: "I am a developer and a tech aficionado from Germany. Love making teeny tiny apps solving tiny problems in life and now learning astrophotography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork ramswaroop on github</a> ;)"
web_design: "CS"
social_urls:
  twitter: "https://www.twitter.com/srsmnsn"
  instagram: "https://www.instagram.com/srsmnsn"
  dribbble: "https://dribbble.com/srsmnsn"
  github: "https://www.github.com/sirsimonson"
