# Base configs
baseurl: "https://astro.sick-simon.de"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "not_yet_implemented"

# UI configs
title: "Astrophotography by Sick Simon"
subtitle: "See the world through my eyes!"
author: "Sick Simon"
header:
 title: "Photography"
 subtitle: "by Sick Simon"
footer:
 name: "Hey there, my name is Simon"
 bio: "I am a developer, space-explorer, synthesizer-cat and love art, tech and slow music."
 github: "Want to explore the universe together? Just reach out to me! I'm passionate for what I am doing and always in search for like-minded. ¯\_(ツ)_/¯"
web_design: "CS"
social_urls:
  twitter: "https://www.twitter.com/srsmnsn"
  instagram: "https://www.instagram.com/srsmnsn"
  dribbble: "https://dribbble.com/srsmnsn"
  github: "https://www.github.com/sirsimonson"
